name: Push Docker Image and Deploy

on:
  push:
    tags:
      - '*'
    branches:
      - main

env:
  MY_IMAGE: "nimaianp75/devops_web:3.4.4"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $MY_IMAGE .

      - name: Push Docker image to Docker Hub
        run: docker push $MY_IMAGE

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up SSH for server
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_SERVER }}

      - name: SSH to Server and Remove Existing Container=port_web
        env:
          ip_add: ${{ secrets.IP_ADD }}
        run: |
              ssh -o StrictHostKeyChecking=no $ip_add 'docker rm -f port_web || true'

      - name: SSH to Server and Pull Docker Image
        env:
          ip_add: ${{ secrets.IP_ADD }}
        run: |
          ssh -o StrictHostKeyChecking=no $ip_add 'docker pull nimaianp75/devops_web:3.4.4'

      - name: SSH to Server and Run Docker Container
        env:
          ip_add: ${{ secrets.IP_ADD }}
        run: |
          ssh -o StrictHostKeyChecking=no $ip_add 'docker run -d -p 80:80 -p 443:443 -v /etc/letsencrypt:/etc/letsencrypt --name port_web nimaianp75/devops_web:3.4.4'
